#!/bin/sh

VERSION="0.18"

docker build -t itsnikolay/testapp:$VERSION -f Dockerfile .
docker run -d -it itsnikolay/testapp:$VERSION bash

docker commit $(docker ps -lq) itsnikolay/testapp:$VERSION
docker push itsnikolay/testapp:$VERSION
